backend:
  adminPassword: bitnami!1234
  adminEmail: vibuser@example.com
  service:
    ports:
      http: 8083
rts:
  service:
    ports:
      http: 8085
serviceAccount:
  automountServiceAccountToken: true
client:
  service:
    type: LoadBalancer
    ports:
      http: 80
  containerSecurityContext:
    runAsUser: 1002
  podSecurityContext:
    fsGroup: 1002
  containerPorts:
    http: 8022
