# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  spring-cloud-dataflow-composed-task-runner:
    image: docker.io/bitnami/spring-cloud-dataflow-composed-task-runner:2
