apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  labels:
    app: airflow-secrets
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
 openmetadata-airflow-password: {{ .Values.airflow_password | quote }}