apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  labels:
    app: mysql-secrets
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
  openmetadata-mysql-password: {{ .Values.mysql_password | quote }}