apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  labels:
    app: postgres-secrets
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
  password: {{ .Values.postgres_password | quote }}