# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  harbor-core:
    image: docker.io/bitnami/harbor-core:2
    ports:
      - 80:8080
    environment:
      - LOG_LEVEL=info
      - CONFIG_PATH=/etc/core/app.conf
      - CORE_SECRET=not-a-secure-core-secret
      - JOBSERVICE_SECRET=not-a-secure-jobservice-secret
    volumes:
      - ./config/core/app.conf:/etc/core/app.conf:ro
      - ./config/core/private_key.pem:/etc/core/private_key.pem:ro
      - harbor-core_data:/data

volumes:
  harbor-core_data:
    driver: local
