# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  gradle:
    image: docker.io/bitnami/gradle:8
    # Overriding entrypoint so the container does not exit and we can run some basic tests
    entrypoint: tail -f /dev/null
    volumes:
      - .:/app
