apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: pod-failure-openldap
  annotations:
    experiment.chaos-mesh.org/pause: "true"
spec:
  schedule: "@every 2m"
  type: "PodChaos"
  historyLimit: 5
  concurrencyPolicy: Forbid
  podChaos:
    action: pod-failure
    duration: 15s
    mode: random-max-percent
    selector:
      labelSelectors:
        app.kubernetes.io/name: openldap-stack-ha
    value: '66' 