# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  fluentd:
    image: docker.io/bitnami/fluentd:1
    ports:
      - '24224:24224'
      - '5140:5140'
    volumes:
      - fluentd_data:/bitnami/fluentd
volumes:
  fluentd_data:
    driver: local
