create database airflow_db;
create user airflow_user with password 'airflow_pass';
grant all privileges on database airflow_db to airflow_user;
grant all on schema public to airflow_user;
ALTER DATABASE airflow_db OWNER TO airflow_user;
create database openmetadata_db;
create user openmetadata_user with password 'openmetadata_pass';
grant all privileges on database openmetadata_db to openmetadata_user;
grant all on schema public to openmetadata_user;
ALTER DATABASE openmetadata_db OWNER TO openmetadata_user;
create database superset_db;
create user superset_user with password 'superset_pass';
grant all privileges on database superset_db to superset_user;
grant all on schema public to superset_user;
ALTER DATABASE superset_db OWNER TO superset_user;
create user rangeradmin with createdb login password 'rangeradmin';
create database ranger with owner rangeradmin;
GRANT ALL PRIVILEGES ON SCHEMA public TO rangeradmin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO rangeradmin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO rangeradmin;
create database trino_db;
create user trino_user with password 'trino_pass';
grant all privileges on database trino_db to trino_user;
grant all on schema public to trino_user;
ALTER DATABASE trino_db OWNER TO trino_user;
CREATE USER rangeradmin WITH PASSWORD 'rangerR0cks!';
CREATE DATABASE ranger;
GRANT ALL PRIVILEGES ON DATABASE ranger TO rangeradmin;
CREATE USER hive WITH PASSWORD 'rangerR0cks!';
CREATE DATABASE hive;
GRANT ALL PRIVILEGES ON DATABASE hive TO hive;
